################################################################################
# General settings
title: Modelling, Uncertainty and Data for Engineers (MUDE)
author: the MUDE Team
logo: _static/MUDE_Logo-small.png

################################################################################
# Notebook execution on compiling
execute:
  execute_notebooks: false
  timeout: 60 
  allow_errors: false

################################################################################
# Sphinx settings
sphinx:
  config:
    # Bibliography style
    bibtex_reference_style: author_year
    # Use newer version of Mathjax for latex equation formatting
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

################################################################################
# Bibliography file
bibtex_bibfiles:
  - _bibliography/references.bib
