name: deploy

on:
  push:
    branches:
      - main
    paths:
      - "book/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "book/**"
      - ".github/workflows/**"

defaults:
  run:
    shell: bash

jobs:
  build-book:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      # Setup virtualenv with caching
      - name: Setup venv
        uses: syphar/restore-virtualenv@v1
        with:
          requirement_files: requirements.txt
    
      # Pip download cache
      - name: Setup pip cache
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # Build the Jupyter Book
      - name: Build book
        run: |
          cd book/
          jupyter-book build .

      # Upload artifact
      - name: Upload HTML
        uses: actions/upload-artifact@v3
        with:
          name: book
          path: book/_build/

  deploy-book:
    if: github.ref == 'refs/heads/main'
    needs: build-book
    runs-on: self-hosted
    steps:

      # Download artifact
      - name: Download HTML
        uses: actions/download-artifact@v3
        with:
          name: book

      # Publish book
      - name: GitHub Pages actions/checkout
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/_build/html