name: deploy

on:
  push:
    branches:
      - main
    paths:
      - "book/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "book/**"
      - ".github/workflows/**"

defaults:
  run:
    shell: bash

jobs:
  build-book:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      # Setup virtualenv with caching
      - name: Setup venv
        uses: syphar/restore-virtualenv@v1
        with:
          requirement_files: requirements.txt
    
      # Pip download cache
      - name: Setup pip cache
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # Build the Jupyter Book
      - name: Build book
        run: |
          cd book/
          jupyter-book build .

      - name: GitHub Pages actions
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/_build/html/