name: test

on:
  pull_request:
    types:
      - [opened, reopened]

jobs:
  test-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      
      - name: Setup venv
        uses: syphar/restore-virtualenv@v1
        with:
          requirement_files: requirements.txt
    
      - name: Setup pip cache
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Test notebooks 
        run: |
          pytest --nbmake 